### ISSUE TITLE
WHOAREYOU sequence number

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/devp2p#114]
If the handshake recipient does not know any ENR of the initiator, what sequence number should they include in the WHOAREYOU packet? I would assume `0`, but this creates a problem if `0` is used as sequence number for new ENRs. I guess the simplest solution is to just start with `1` and perhaps that's the intention, but I couldn't find this being mentioned anywhere.

**Comment by fjl** [comment]
Yes, they should send zero in this case.
