### ISSUE TITLE
discv5: define ECDH better

### ISSUE THREAD

**Issue by fjl** [ethereum/devp2p#116]
It would be better to define ECDH `agree` to match [libsecp256k1](https://github.com/bitcoin-core/secp256k1/blob/master/src/modules/ecdh/main_impl.h). This way people can just use the library without worrying about it too much.

The spec should also define the wire format of `ephemeral-pubkey`.

**Comment by AgeManning** [comment]
Also, specify the ECDSA algorithm. I was using RFC3278 which is DER-encoded. The go implementation uses r | s (which makes sense in hindsight as it matches ENR sigs.
