### ISSUE TITLE
discv5: REGTOPIC Request. How to pass topic value?

### ISSUE THREAD

**Issue by annashunko** [ethereum/devp2p#124]
According to the [REGTOPIC Request ](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#regtopic-request-0x05) description, regtopic message data are a node record and a ticket. If it is the first attempt the ticket is empty (0x80).
Shouldn't we pass the topic value as well is this message? How does the recipient understand for which topic to create a ticket?

**Comment by fjl** [comment]
The ticket should probably contain the topic already.
