### ISSUE TITLE
rlpx.md: spec is ambiguous wrt first msg after handshake

### ISSUE THREAD

**Issue by gsalgado** [ethereum/devp2p#128]
> The "p2p" capability is present on all connections. After the initial handshake, both sides of the connection must send a Hello message. Upon receiving the Hello message a session is active and any other message may be sent. Implementations must ignore any difference in protocol version for forward-compatibility reasons. When communicating with a peer of lower version, implementations should try to mimic that version.

> At any time, a Disconnect message may be sent.

In practice, a maxed-out geth node will send a `Disconnect` msg before the Hello, which kind of makes more sense than sending a `Hello` just to follow it with a `Disconnect`, but then the spec should probably be updated to reflect that after the initial handshake either a `Hello` or a `Disconnect` can be sent

**Comment by fjl** [comment]
Please check #129
