### ISSUE TITLE
discv5: use compressed ephemeral key in handshake

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/devp2p#135]
It doesn't seem to be explicitly documented, but apparently we use the 64 byte uncompressed format for sending ephemeral public keys (according to the wire test vectors). In ENRs we use the 33 byte compressed format. I think this is discrepancy is unnecessarily confusing.

ENRs are already EIPed, but would it be too late already to change the wire protocol to use the compressed format?

**Comment by fjl** [comment]
No, it's not too late to change the wire protocol. I can create a PR to change it, but we need to notify all implementers. Would be good to have a list of implementations :)

**Comment by fjl** [comment]
The point compression will add a bit of extra CPU time to the handshake, need to benchmark how much.
