### ISSUE TITLE
LES: networkId for Status protocol message

### ISSUE THREAD

**Issue by ryanio** [ethereum/devp2p#174]
Currently the LES spec under [`Status (0x00)`](https://github.com/ethereum/devp2p/blob/master/caps/les.md#status-0x00) says:

> `"networkId"` `P`: should be 0 for testnet, 1 for mainnet.

This doesn't seem correct, should the `networkId` be the `chainId` as specified by [EIP-155](https://eips.ethereum.org/EIPS/eip-155#list-of-chain-ids) /  [chainid.network](https://chainid.network/) ?

**Comment by fjl** [comment]
networkID and chain ID are technically distinct, but we should probably
update the spec to list the correct chain IDs as in the eth protocol spec.
