### ISSUE TITLE
Ethereum and JavaScript Integration

### ISSUE THREAD

**Issue by FrostyTheSouthernSnowman** [ethereum/devp2p#193]

**Comment by FrostyTheSouthernSnowman** [comment]
Would it be possible to add an additional protocol, or just extend the current one for browser-side JavaScript to be able to connect to the Ethereum network. It might also require a new node type that doesn't download any chain data. I am aware that such a node might not be possible, but at least just download the minimal amount for it to run solidity code. If it can run solidity, then the solidity could handle everything else.

**Comment by fjl** [comment]
See also: https://github.com/ethereum/devp2p/issues/166

**Comment by FrostyTheSouthernSnowman** [comment]
Thanks
