### ISSUE TITLE
Error in DiscV4 documentation

### ISSUE THREAD

**Issue by boukestam** [ethereum/devp2p#194]
I've going through this documentation for a side project and I think I found an issue in the Node Discovery Protocol docs.
In the [FindNode section](https://github.com/ethereum/devp2p/blob/master/discv4.md#findnode-packet-0x03) it says the following:

>The target is a 65-byte secp256k1 public key.

But after some debugging and testing and looking at the [ethereumjs-devp2p repository](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/src/dpt/message.ts) I found out it's actually supposed to be the ```64-byte node id```.

**Comment by fjl** [comment]
Thanks! It's fixed now.
