### ISSUE TITLE
best way to learn ethereum network

### ISSUE THREAD

**Issue by huahuayu** [ethereum/devp2p#197]
Hi, in general I am familiar with ethereum, I have several year experience work with it, now I want to study ethereum network protocol, I googled and watched some video in youtube, then try to understand this repo, but can't understand it yet.

Could you give some guidelines for learn ethereum network, and the best way to test it?

**Comment by fjl** [comment]
All information about Ethereum 1.0 network protocols is here in this repo.

The Ethereum network uses two protocols:

- [discv4](https://github.com/ethereum/devp2p/blob/master/discv4.md) for finding other nodes
- [RLPx](https://github.com/ethereum/devp2p/blob/master/rlpx.md) + [eth](https://github.com/ethereum/devp2p/blob/master/caps/eth.md) to transfer blockchain data

**Comment by huahuayu** [comment]
Thanks @fjl !

Since dev2p2 is described as `Utilities to interact with nodes on the networking layer, without running a full blockchain.` If I am not care about history data, can I directly use it as lite node to join ethereum network.

the functions I want achieve:
- always keep the connection with other nodes
- receive new tx & broadcast new txs, like a relay
- only cache like 100 blocks data

**Comment by fjl** [comment]
> Since dev2p2 is described as Utilities to interact with nodes on the networking layer, without running a full blockchain

I think you mean go-ethereum's cmd/devp2p here. It's a command-line tool for p2p protocol development and research.

We do not provide the kind of implementation you are asking about in go-ethereum, and also not here. In this repo here, we maintain only the *specifications* for network protocols. It's a place with information for people who implement the protocol. If you want to achieve this kind of light node, you need to implement it yourself using the specifications as a guide.

**Comment by huahuayu** [comment]
OK, I see, thanks for the clarification!
