### ISSUE TITLE
nodes with multiple IP address

### ISSUE THREAD

**Issue by wanderer** [ethereum/devp2p#24]
How would you deal with nodes that have multiple address?

**Comment by subtly** [comment]
We don't. The protocol only supports one node-id per endpoint.

**Comment by wanderer** [comment]
@subtly feature for the future? or is there a reason for one per endpoint?

**Comment by subtly** [comment]
@wanderer I missed your question. I think support of multiple addresses is out of scope. The endpoint is recorded (determined) by the remote side of the connection and acknowledged by the other side. Thus, discovery endpoints are dynamic and implicit; as they can't be queried, they are also uniform.

If a node has multiple endpoints and connectivity is established to both using the same NodeId then the result will be the graph of nodes for one endpoint propagating a different address than what is propagated by the graph connected to the other endpoint. Assuming the uniform properties of discovery hold, this shouldn't pose a problem.
