### ISSUE TITLE
Why does Ethereum uses a structured overlay for broadcasting while Bitcoin doesn't?

### ISSUE THREAD

**Issue by derekchiang** [ethereum/devp2p#36]
Does anyone have insights into why Ethereum uses a structured overlay (Kademlia) for broadcasting while Bitcoin uses a randomized graph?

**Comment by fjl** [comment]
I'm super late to answering this, but Ethereum doesn't use a structured overlay for broadcasting. TCP connectivity between nodes is unstructured. I hope this answers your question.
