### ISSUE TITLE
EIP-868: Node Discovery v4 ENR Extension

### ISSUE THREAD

**Issue by fjl** [ethereum/devp2p#44]
https://eips.ethereum.org/EIPS/eip-868

This issue is for discussions of the discovery v4 ENR extension.

**Comment by gumb0** [comment]
Note: test vectors for extending Ping and Pong packets listed in EIP-8 I think are invalid from the point of view of this extension, because they have RLP-list in place of the new extension field, not integer like here.

I mean these vectors:
```
ping packet with version 555, additional list elements and additional random data:
	577be4349c4dd26768081f58de4c6f375a7a22f3f7adda654d1428637412c3d7fe917cadc56d4e5e
	7ffae1dbe3efffb9849feb71b262de37977e7c7a44e677295680e9e38ab26bee2fcbae207fba3ff3
	d74069a50b902a82c9903ed37cc993c50001f83e82022bd79020010db83c4d001500000000abcdef
	12820cfa8215a8d79020010db885a308d313198a2e037073488208ae82823a8443b9a355c5010203
	040531b9019afde696e582a78fa8d95ea13ce3297d4afb8ba6433e4154caa5ac6431af1b80ba7602
	3fa4090c408f6b4bc3701562c031041d4702971d102c9ab7fa5eed4cd6bab8f7af956f7d565ee191
	7084a95398b6a21eac920fe3dd1345ec0a7ef39367ee69ddf092cbfe5b93e5e568ebc491983c09c7
	6d922dc3

pong packet with additional list elements and additional random data:
	09b2428d83348d27cdf7064ad9024f526cebc19e4958f0fdad87c15eb598dd61d08423e0bf66b206
	9869e1724125f820d851c136684082774f870e614d95a2855d000f05d1648b2d5945470bc187c2d2
	216fbe870f43ed0909009882e176a46b0102f846d79020010db885a308d313198a2e037073488208
	ae82823aa0fbc914b16819237dcd8801d7e53f69e9719adecb3cc0e790c57e91ca4461c9548443b9
	a355c6010203c2040506a0c969a58f6f9095004c0177a6b47f451530cab38966a25cca5cb58f0555
	42124e
```
Not sure if we should update EIP-8.

**Comment by fjl** [comment]
Geth implementation: https://github.com/ethereum/go-ethereum/pull/19540

**Comment by atoulme** [comment]
I have made a first pass at implementing this with Apache Tuweni.
How can I test this against geth easily?

**Comment by fjl** [comment]
Just connect your node to it on discovery. Geth will ask for the record after a while. Maybe use `--netrestrict 127.0.0.1/24` with geth so it doesn't fill the table with Internet nodes.

**Comment by fjl** [comment]
discv4 spec updated in #119. Closing this now because implementations of the spec have been live in Geth and Aleth for a while.

**Comment by fulldecent** [comment]
Can this please be implemented in two or more competing implementations, and referenced in the EIP, before this is published as final status?

**Comment by atoulme** [comment]
Implemented in Tuweni and Besu.

**Comment by fulldecent** [comment]
Excellent, thank you. Can this please be noted in the EIP text?
