### ISSUE TITLE
Move subprotocol specs into this repo

### ISSUE THREAD

**Issue by fjl** [ethereum/devp2p#47]
I would like to have all known subprotocol specs in one place. Protocols I know of are

- `eth`: everyone implements this one
- `les`: geth and a few others have it
- `shh`: many versions, it's unclear to me which one is canonical
- `bzz`, `hive`, `discovery`, `stream`: part of swarm

**Comment by bobsummerwill** [comment]
@fjl on SHH ...
https://www.reddit.com/r/ethereum/comments/89xcvb/whisper_compatibility_geth_parity/?st=jmd0bwtt&sh=bd994d2b

**Comment by 5chdn** [comment]
`pip` in https://wiki.parity.io/The-Parity-Light-Protocol-(PIP)

**Comment by fjl** [comment]
Thank you! I hope you don't mind if I copy those specs to this repo.

**Comment by 5chdn** [comment]
I don't mind. It's all CC-BY-SA, but should be CC-0 really for the specs.

Source MDs at https://github.com/paritytech/wiki

**Comment by FrankSzendzielarz** [comment]
Note that protocol names like 'stream' are inconsistent with the protocol spec ("cap1: B_3")

**Comment by FrankSzendzielarz** [comment]
@fjl I ran a stabilized version of that crawler yesterday evening. I processed the output to show what caps and versions I got by crawling AND establishing handshake successfully. This is the result of about 5000 nodes found:


eth - 63
--
eth - 62
etz - 64
etz - 63
etz - 62
exp - 63
exp - 62
bzz - 7
hive - 6
stream - 7
pss - 2
pip - 1
par - 1
par - 2
par - 3
etf - 63
etf - 62
anr - 62
anr - 63
glx - 62
glx - 63
istanbul - 64
les - 2
les - 1
wolk - 66
pchain - 64
mc - 63
mc - 62
dbix - 63
dbix - 62
ele - 63
ele - 62
etrue - 63
etrue - 62
shh - 6
ddm - 63
shh - 2
shh - 5
ctxc - 63
ctxc - 62
wsh - 63
wsh - 62
ur - 63
ur - 62
stream - 8
ddm - 62
bzz - 0
pwh - 6
adh - 63
adh - 62
laz - 63
laz - 62
okc - 63
okc - 62

**Comment by fjl** [comment]
We should remove the three-letter restriction from the spec.

**Comment by fjl** [comment]
PR to add eth: https://github.com/ethereum/devp2p/pull/62

**Comment by fjl** [comment]
PR to add les/2: #64

**Comment by fjl** [comment]
Assigned @gballet because he agreed to move the whisper spec.

**Comment by fjl** [comment]
Assigned @gballet because he agreed to move the whisper spec.

**Comment by FrankSzendzielarz** [comment]
I am looking into light stuff at the mo, I'll check the licensing and throw the parity light stuff in here too later

**Comment by fjl** [comment]
Whisper will not move here, and I think we have everything. It would be nice to get waku in here, since it uses RLPx for now.

@decanus if you want the RLPx version of waku in this repo, and you're willing to put up with the markdown linter we have on here, go ahead and add it :).
