### ISSUE TITLE
p2p effort consolidation

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/devp2p#59]
It is becoming difficult to track the different p2p efforts.

We now seem to have many different groups working on devp2p wire protocols in different repos.

Some people working on eth2 p2p:
https://github.com/ethresearch/p2p/issues

General repo intended to be everything ethereum p2p:
https://github.com/ethereum/devp2p/

Discovery protocol for all future versions:
https://github.com/ethereum/devp2p/tree/master/discv5

Another group of people working on eth2.0 p2p:
https://github.com/ethereum/eth2.0-specs/issues/692

There are also now multiple proposed wire formats for different places. RLP, SSZ, SOS, SSS, each with differing types of design goals and differing clarity in design goals.

Recent convo with @Felix Lange (fjl) we agreed that ethereum/devp2p should be the label for 'all things p2p' in Ethereum. Do we agree with that , and if so, I would like to kick off some effort to consolidate and focus these groups- eg: by moving the different draft specs under ethereum/devp2p and having all the stakeholders converse there.

**Comment by Mikerah** [comment]
This may seem irrelevant but still using the term _devp2p_ is outdated considering that the networking stack is going to be _libp2p_. Moreover, as people are confused between the differences between the 2, I think a consistent renaming should be done.

As for what repo to use, the whole purpose of https://github.com/ethresearch/p2p/issues was for discussions and ideas. Anything concrete like the wire protocol was meant to be an issue in the eth2.0-specs repo. If ethereum/devp2p become the repo for all things p2p in Ethereum, would it also include these discussions?

**Comment by fjl** [comment]
We discussed this in the last eth2.0 implementers call and nobody spoke up against transferring p2p discussions here. So I guess we'll just do it.

I'll see how the repo can be reorganized to avoid confusion between eth1.0 and eth2.0.

**Comment by fjl** [comment]
It looks like nobody is looking at https://github.com/ethresearch/p2p anymore. eth 2.0 networking discussion seems to be happening in the [eth2.0-specs tracker](https://github.com/ethereum/eth2.0-specs/issues) now. See [the networking label](https://github.com/ethereum/eth2.0-specs/issues?q=is%3Aopen+is%3Aissue+label%3Anetworking) there.
