### ISSUE TITLE
update: nat traversal

### ISSUE THREAD

**Issue by subtly** [ethereum/devp2p#6]
In it's current form the node discovery protocol works by ignoring endpoint information provided in ping packets. A feedback system should be designed so that nodes can be notified when nat is detected and keepalives are employed to keep the socket open (when appropriate); this can be added to the Pong packet. The functionality of utp/stun/ice/nat-pmp/upnp should be considered.

**Comment by fjl** [comment]
We're in the process of adding this to go-ethereum. See https://twurst.com/articles/stun-without-trust.html for more details.

**Comment by fjl** [comment]
This is now part of the discovery v5 spec.

**Comment by subtly** [comment]
Awesome 👍
