### ISSUE TITLE
Node discovery and cademlia should use hash of public key as address 

### ISSUE THREAD

**Issue by zelig** [ethereum/devp2p#8]
Since no independent bits assumption is guaranteed on EC public keys
peers' public key needs to be hashed to derive a node's address used in cademlia routing.
Also, in order to help storage persistence of address-driven dht nodes the address should be derived from a permanent public key not an autogenerated one.

**Comment by zelig** [comment]
please review https://github.com/ethereum/go-ethereum/pull/312

**Comment by subtly** [comment]
Fixed in 562e51c

**Comment by subtly** [comment]
See also issue #5
