### ISSUE TITLE
discv5: transport pre-negotiation packet (LETSTALK)

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/devp2p#83]
This is more of a discussion starter / idea than a concrete proposal:

Although it's not yet documented, the discv5 spec seems to be evolving towards encrypted aes-gcm based communication, rather than obfuscation and recoverable signatures....

Assuming we get there, the following idea:

0) The discv5 protocol now involves a quick handshake of secrets and keys from ENRs, before any kind of Kademlia communication can happen
1) Aes-gcm allows parallel communication
2) Can the same shared secrets and cypher ('channel') be re-used for TCP?
3) Because it is aes-gcm, large messages can be streamed.
4) This would allow ETH (etc) protocol to work without handshake.

Regarding libp2p - other implementations that want to use libp2p for flexibility and interoperability could do so (eg: polkadot) - and they could be able to communicate with nodes that use such a mechanism as proposed above (???). Eth 2.0 will use discovery v5 anyway in all likelihood.

However, for implementations that want to deliver a single performance optimized method of networking that employs a common udp+tcp handshake, the discovery 'channel' (pardon the pun) and this aes-gcm encrypted communication would be all that was needed, as long as the transport was reliable. Which particular transport outside of TCP could in future be determined by ENR (eg: ETH = tcp 30303, http 80 etc)

Thoughts?

**Comment by fjl** [comment]
If needed, we can add a protocol message like `LETSTALK` to help with establishing communication through another transport protocol. This kind of message can relay key material or initialization data for a new connection. 

Regarding the secrets, I think the outputs of the handshake should NOT be reused in any way. It's fragile enough as-is.

**Comment by fjl** [comment]
The need for this is now becoming more urgent since @zsfelfoldi wants to add pre-negotiation to les. 

Here's the use case: when a client finds a server, it needs to establish a TCP connnection and run the handshake only to find out that the provided service is too expensive or not enough capacity is available. Discovery should be able help with this issue by providing enough information to make an informed connectivity decision.

With the LETSTALK packet from the previous comment, pre-negotiation would look as follows:

```
A -> B   LETSTALK [<req-id>, "les"]
A <- B   LETSTALK [<req-id>, <server-info>]
```

**Comment by fjl** [comment]
We might need a better name for this new packet pair, and a clearer definition of its semantics.

**Comment by zilm13** [comment]
@fjl do you have a Geth fork with all in it?
