### ISSUE TITLE
Clarify reasons behind restricting discovery to UDP

### ISSUE THREAD

**Issue by dryajov** [ethereum/devp2p#89]
Discovery v5 (and v4) is restricted to UDP only, could the reasons behind that decision be clearly stated. 

This is a limiting factor in the context of browser runtimes (#87 and as brought up in #71).

**Comment by FrankSzendzielarz** [comment]
Thoughts from me on this so far https://github.com/ethereum/devp2p/issues/87#issuecomment-486161337

**Comment by fjl** [comment]
There is now a section in the rationale addressing this issue.
