### ISSUE TITLE
spec / implementation discrepancy for ping and neighbours packets

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/devp2p#9]
spec of structure of ping & neighbors packets not according to implementations. or the other way round. 

https://github.com/ethereum/devp2p/commit/5275f5669e165ebf4cef49bf9404cc891021e3c5#diff-9999caa615e6404632c336aa8177c9edR108

**Comment by subtly** [comment]
This is correct -- both clients are out of spec and using a placeholder for interop. Created issue #10.
